Repository rdsaliba/notorious-eng, pull requests merged in 2020-11, with the labels that each got.

#71 RUL Prediction
  .DS_Store
  .idea/compiler.xml
  Dataset/.DS_Store
  Dataset/Converted/engine1.arff
  Dataset/Converted/engine2.arff
  Dataset/Converted/engine3.arff
  Dataset/Real RUL/engine1.txt
  Dataset/Real RUL/engine2.txt
  Dataset/Real RUL/engine3.txt
  src/main/java/com/cbms/Health_Assessment/HealthAssesement.java
  src/main/java/com/cbms/RUL_Models/LinearRegressionModelImpl.java
  src/main/java/com/cbms/app/StartupController.java
  src/test/java/RUL_Models/RootMeanSquaredError.java
  src/test/java/RUL_Models/testModel.java
Labels: Linear Regression

#82 28 30 data cleaning enhancements
  Dataset/Converted/train_FD001_filtered.arff
  src/main/java/com/cbms/app/StartupController.java
  src/main/java/com/cbms/preprocessing/DataPrePreprossesorController.java
  src/main/java/com/cbms/preprocessing/DataPreProcessor.java
  src/main/java/com/cbms/preprocessing/DataPreProcessorImpl.java
Labels: Data Processing, enhancement

#104 Bug fix/new asset type needed changes in queries
  src/main/java/com/cbms/app/item/Asset.java
  src/main/java/com/cbms/source/local/Database.java
  src/main/java/com/cbms/ui/controller/SystemInfoController.java
  src/main/java/com/cbms/ui/controller/SystemsController.java
Labels: BugFix, Database

#116 #112 removing dataset concept
  src/main/resources/script/cbms_scriptsV4/V4.02.sql
Labels: Pull Request

#117 66 68 ui
  src/main/java/com/cbms/ui/controller/AddSystemController.java
  src/main/java/com/cbms/ui/controller/SystemInfoController.java
  src/main/java/com/cbms/ui/controller/SystemsController.java
  src/main/java/com/cbms/ui/controller/UIUtilities.java
  src/main/resources/SystemInfo.fxml
  src/main/resources/Systems.fxml
  src/main/resources/css/systems.css
Labels: UI, refactoring

#114 Database connection bug
  .idea/sqldialects.xml
  src/main/java/com/cbms/app/Main.java
  src/main/java/com/cbms/app/ModelController.java
  src/main/java/com/cbms/source/local/Database.java
  src/main/java/com/cbms/source/local/DatabaseConnection.java
Labels: Pull Request

#119 System Testing setup
  e2e/com/cbms/app/TextFXBase.java
  pom.xml
Labels: Pull Request
