Repository rdsaliba/notorious-eng, pull requests merged in 2021-01, with the labels that each got.

#149 107 add system type
  src/main/java/com/cbms/app/item/AssetType.java
  src/main/java/com/cbms/app/item/AssetTypeParameter.java
  src/main/java/com/cbms/source/local/AssetDAO.java
  src/main/java/com/cbms/source/local/AssetDAOImpl.java
  src/main/java/com/cbms/source/local/AssetTypeDAO.java
  src/main/java/com/cbms/source/local/AssetTypeDAOImpl.java
  src/main/java/com/cbms/ui/controller/AddSystemTypeController.java
  src/main/resources/AddSystemType.fxml
  src/main/resources/css/style.css
Labels: Pull Request, UI

#133 132_DL4J_Integration_LSTM
  .gitignore
  .idea/jarRepositories.xml
  local-maven-repo/nz/ac/waikato/cms/weka/wekaDeeplearning4j/1.7.0/wekaDeeplearning4j-1.7.0.jar
  local-maven-repo/nz/ac/waikato/cms/weka/wekaDeeplearning4j/1.7.0/wekaDeeplearning4j-1.7.0.jar.md5
  local-maven-repo/nz/ac/waikato/cms/weka/wekaDeeplearning4j/1.7.0/wekaDeeplearning4j-1.7.0.jar.sha1
  local-maven-repo/nz/ac/waikato/cms/weka/wekaDeeplearning4j/1.7.0/wekaDeeplearning4j-1.7.0.pom
  local-maven-repo/nz/ac/waikato/cms/weka/wekaDeeplearning4j/1.7.0/wekaDeeplearning4j-1.7.0.pom.md5
  local-maven-repo/nz/ac/waikato/cms/weka/wekaDeeplearning4j/1.7.0/wekaDeeplearning4j-1.7.0.pom.sha1
  local-maven-repo/nz/ac/waikato/cms/weka/wekaDeeplearning4j/maven-metadata.xml
  local-maven-repo/nz/ac/waikato/cms/weka/wekaDeeplearning4j/maven-metadata.xml.md5
  local-maven-repo/nz/ac/waikato/cms/weka/wekaDeeplearning4j/maven-metadata.xml.sha1
  pom.xml
  src/main/java/com/cbms/app/ModelController.java
  src/main/java/com/cbms/rul/models/LSTMModelImpl.java
  src/main/java/com/cbms/rul/models/LinearRegressionModelImpl.java
  src/main/java/com/cbms/source/local/Database.java
  src/main/java/com/cbms/source/local/DatabaseConnection.java
Labels: LSTM, Pull Request

#152 134 refactoring UI
  .idea/misc.xml
  pom.xml
  src/main/java/com/cbms/app/Main.java
  src/main/java/com/cbms/app/item/Asset.java
  src/main/java/com/cbms/app/item/AssetAttribute.java
  src/main/java/com/cbms/app/item/AssetInfo.java
  src/main/java/com/cbms/app/item/AssetType.java
  src/main/java/com/cbms/app/item/Measurement.java
  src/main/java/com/cbms/app/item/RULEstimate.java
  src/main/java/com/cbms/source/local/AssetDAOImpl.java
  src/main/java/com/cbms/source/local/AssetTypeDAO.java
  src/main/java/com/cbms/source/local/AssetTypeDAOImpl.java
  src/main/java/com/cbms/source/local/Database.java
  src/main/java/com/cbms/source/local/DatabaseConnection.java
  src/main/java/com/cbms/ui/controller/AddSystemController.java
  src/main/java/com/cbms/ui/controller/SystemInfoController.java
  src/main/java/com/cbms/ui/controller/SystemsController.java
  src/main/resources/AddSystem.fxml
  src/main/resources/SystemInfo.fxml
  src/main/resources/Systems.fxml
  src/main/resources/css/addSystem.css
  src/main/resources/css/style.css
  src/main/resources/css/systems.css
  src/main/resources/imgs/outline_exit_to_app_white_18dp.png
Labels: BugFix, UI, refactoring

#153 108 Load the database in real-time
  src/main/java/com/cbms/app/Main.java
  src/main/java/com/cbms/source/local/AssetDAOImpl.java
Labels: Database, High Priority, Pull Request, enhancement

#154 12_Evaluate_LSTM
  Dataset/Converted/test1Shortened.arff
  Dataset/Converted/test_FD001_withRUL.arff
  Dataset/Converted/train_FD001_withRUL.arff
  src/test/java/rul_models/testModel.java
Labels: LSTM, Testing

#158 109 real time calculate rul
  src/main/java/com/cbms/app/Main.java
  src/main/java/com/cbms/app/ModelController.java
  src/main/java/com/cbms/source/local/AssetDAO.java
  src/main/java/com/cbms/source/local/AssetDAOImpl.java
  src/main/java/com/cbms/source/local/AttributeDAO.java
  src/main/java/com/cbms/source/local/AttributeDAOImpl.java
  src/main/java/com/cbms/ui/controller/SystemInfoController.java
  src/main/java/com/cbms/ui/controller/SystemsController.java
Labels: Pull Request, UI, enhancement

#185 11 add asset v2
  .gitignore
  JavaFXUserInterface/src/main/java/AddSystemController.java
  JavaFXUserInterface/src/main/resources/AddSystem.fxml
  JavaFXUserInterface/src/test/java/AddSystemControllerTest.java
  Server/src/main/java/app/item/AssetInfo.java
  Server/src/main/java/local/AssetDAO.java
  Server/src/main/java/local/AssetDAOImpl.java
  Server/src/main/java/local/AssetTypeDAO.java
  Server/src/main/java/local/AssetTypeDAOImpl.java
Labels: Low Priority, Pull Request, UI

#188 #87 Ascending/Descending Asset List by RUL
  JavaFXUserInterface/src/main/java/SystemsController.java
  JavaFXUserInterface/src/main/resources/Systems.fxml
  JavaFXUserInterface/src/main/resources/css/style.css
  Server/src/main/java/app/ModelController.java
  Server/src/main/java/local/AssetDAOImpl.java
Labels: Pull Request

#189 Sprint 5 SonarQube Refactoring
  JavaFXUserInterface/src/e2e/com/cbms/app/TextFXBase.java
  JavaFXUserInterface/src/main/java/AddSystemController.java
  JavaFXUserInterface/src/main/java/AddSystemTypeController.java
  JavaFXUserInterface/src/main/java/CBMSApplication.java
  JavaFXUserInterface/src/main/java/SystemInfoController.java
  JavaFXUserInterface/src/main/java/SystemTypeController.java
  JavaFXUserInterface/src/main/java/SystemsController.java
  RealTimeDemo/pom.xml
  Server/pom.xml
  Server/src/main/java/app/ModelController.java
  Server/src/main/java/app/item/Asset.java
  Server/src/main/java/app/item/AssetInfo.java
  Server/src/main/java/app/item/RULEstimate.java
  Server/src/main/java/local/AssetDAO.java
  Server/src/main/java/local/AssetDAOImpl.java
  Server/src/main/java/local/AssetTypeDAOImpl.java
  Server/src/main/java/local/AttributeDAOImpl.java
  Server/src/main/java/local/ModelDAOImpl.java
  Server/src/main/java/local/RulDAOImpl.java
  Server/src/main/java/preprocessing/DataPreProcessor.java
  Server/src/main/java/preprocessing/DataPreProcessorImpl.java
  Server/src/main/java/rul/assessment/HealthAssessment.java
  Server/src/main/java/rul/models/LSTMModelImpl.java
  Server/src/main/java/rul/models/LinearRegressionModelImpl.java
Labels: Pull Request

#190 167 General asset type info
  JavaFXUserInterface/src/main/java/AddSystemController.java
  JavaFXUserInterface/src/main/java/AddSystemTypeController.java
  JavaFXUserInterface/src/main/java/SystemInfoController.java
  JavaFXUserInterface/src/main/java/SystemTypeController.java
  JavaFXUserInterface/src/main/java/SystemTypeEditController.java
  JavaFXUserInterface/src/main/java/SystemTypeInfoController.java
  JavaFXUserInterface/src/main/java/SystemsController.java
  JavaFXUserInterface/src/main/java/UIUtilities.java
  JavaFXUserInterface/src/main/resources/AddSystem.fxml
  JavaFXUserInterface/src/main/resources/AddSystemType.fxml
  JavaFXUserInterface/src/main/resources/SystemInfo.fxml
  JavaFXUserInterface/src/main/resources/SystemTypeEdit.fxml
  JavaFXUserInterface/src/main/resources/SystemTypeInfo.fxml
  JavaFXUserInterface/src/main/resources/SystemTypeList.fxml
  JavaFXUserInterface/src/main/resources/Systems.fxml
  JavaFXUserInterface/src/main/resources/css/style.css
  JavaFXUserInterface/src/main/resources/css/systemTypeInfo.css
  JavaFXUserInterface/src/main/resources/imgs/outline_type_white.png
  JavaFXUserInterface/src/main/resources/imgs/system_type_engine.png
  JavaFXUserInterface/src/main/resources/imgs/unknown_system_type.png
Labels: Pull Request

#187 Us110 raw data
  JavaFXUserInterface/src/main/java/SystemInfoController.java
  JavaFXUserInterface/src/main/resources/SystemInfo.fxml
  JavaFXUserInterface/src/main/resources/css/systems.css
Labels: Pull Request

#195 #48 delete a system type
  JavaFXUserInterface/src/main/java/SystemTypeController.java
  JavaFXUserInterface/src/main/java/SystemTypeInfoController.java
  JavaFXUserInterface/src/main/java/SystemTypeList.java
  JavaFXUserInterface/src/test/java/RemoveSystemTypeTest.java
  Server/src/main/java/local/AssetTypeDAO.java
  Server/src/main/java/local/AssetTypeDAOImpl.java
Labels: Pull Request, enhancement

#197 #196 Fixed Add System bug.
  JavaFXUserInterface/src/main/resources/AddSystem.fxml
Labels: Pull Request, bug

#211 88 real time raw data
  JavaFXUserInterface/src/main/java/SystemInfoController.java
  Server/src/main/java/local/AssetTypeDAOImpl.java
  Server/src/main/java/rul/models/LinearRegressionModelImpl.java
Labels: Pull Request

#212 194 unit testing
  JavaFXUserInterface/src/main/java/CBMSApplication.java
  JavaFXUserInterface/src/main/resources/AddSystem.fxml
  JavaFXUserInterface/src/main/resources/SystemInfo.fxml
  JavaFXUserInterface/src/main/resources/SystemTypeList.fxml
  JavaFXUserInterface/src/main/resources/Systems.fxml
  JavaFXUserInterface/src/test/java/AddSystemControllerTest.java
  JavaFXUserInterface/src/test/java/AddSystemTypeControllerTest.java
  JavaFXUserInterface/src/test/java/CBMSApplicationTest.java
  JavaFXUserInterface/src/test/java/SystemInfoControllerTest.java
  JavaFXUserInterface/src/test/java/SystemTypeInfoControllerTest.java
  JavaFXUserInterface/src/test/java/SystemsControllerTest.java
  Server/pom.xml
  Server/src/main/java/app/ModelController.java
  Server/src/main/java/app/item/Asset.java
  Server/src/main/java/app/item/AssetTypeParameter.java
  Server/src/main/java/app/item/Measurement.java
  Server/src/main/java/app/item/TrainedModel.java
  Server/src/main/java/local/AssetDAO.java
  Server/src/main/java/local/AssetDAOImpl.java
  Server/src/main/java/local/ModelDAO.java
  Server/src/main/java/local/ModelDAOImpl.java
  Server/src/main/java/preprocessing/DataPreProcessorImpl.java
  Server/src/main/java/rul/models/LinearRegressionModelImpl.java
  Server/src/test/java/app/item/AssetAttributeTest.java
  Server/src/test/java/app/item/AssetInfoTest.java
  Server/src/test/java/app/item/AssetTest.java
  Server/src/test/java/app/item/AssetTypeParameterTest.java
  Server/src/test/java/app/item/AssetTypeTest.java
  Server/src/test/java/app/item/ItemTest.java
  Server/src/test/java/app/item/MeasurementTest.java
  Server/src/test/java/app/item/TrainedModelTest.java
  Server/src/test/java/assessment/HealthAssessmentTest.java
  Server/src/test/java/assessment/RecommendationAssessmentTest.java
  Server/src/test/java/local/DatabaseTest.java
  Server/src/test/java/preprocessing/reductionTest.java
  Server/src/test/java/rul/models/LSTMRegressionTest.java
  Server/src/test/java/rul/models/LinearRegressionTest.java
  Server/src/test/java/rul_models/RootMeanSquaredError.java
  Server/src/test/java/rul_models/testModel.java
  Server/src/test/resources/FD01_Test_RUL.arff
  Server/src/test/resources/FD01_Train_RUL.arff
Labels: Pull Request
