Repository rdsaliba/notorious-eng, pull requests merged in 2021-03, with the labels that each got.

#275 F12 Associating a model to an Asset Type
  .DS_Store
  JavaFXUserInterface/src/main/java/Controllers/AssetTypeInfoController.java
  JavaFXUserInterface/src/main/java/Utilities/ModelPanes.java
  JavaFXUserInterface/src/main/java/external/AssetDAO.java
  JavaFXUserInterface/src/main/java/external/AssetDAOImpl.java
  JavaFXUserInterface/src/main/java/external/ModelDAO.java
  JavaFXUserInterface/src/main/java/external/ModelDAOImpl.java
  JavaFXUserInterface/src/main/resources/AssetTypeInfo.fxml
  JavaFXUserInterface/src/main/resources/css/assetTypeInfo.css
  JavaFXUserInterface/src/test/java/UnitTests/Controllers/AssetTypeInfoControllerTest.java
  JavaFXUserInterface/src/test/java/UnitTests/Utilities/ModelPanesTest.java
  JavaFXUserInterface/src/test/java/UnitTests/external/AssetDAOTest.java
  JavaFXUserInterface/src/test/java/UnitTests/external/ModelDAOTest.java
  Server/src/main/java/app/item/Model.java
  Server/src/test/java/UnitTests/app/item/ModelTest.java
Labels: Pull Request, refactoring

#282 258 Splash Screen
  JavaFXUserInterface/src/main/java/CBMSApplication.java
  JavaFXUserInterface/src/main/java/SplashScreenPreloader.java
  JavaFXUserInterface/src/main/resources/SplashScreen.fxml
  JavaFXUserInterface/src/main/resources/css/style.css
  JavaFXUserInterface/src/main/resources/imgs/splash_screen_image.png
Labels: Pull Request

#283 #222 parametrize models
  Server/src/main/java/app/ModelController.java
  Server/src/main/java/app/item/parameter/BoolParameter.java
  Server/src/main/java/app/item/parameter/FloatParameter.java
  Server/src/main/java/app/item/parameter/IntParameter.java
  Server/src/main/java/app/item/parameter/ListParameter.java
  Server/src/main/java/app/item/parameter/Parameter.java
  Server/src/main/java/app/item/parameter/StringParameter.java
  Server/src/main/java/rul/models/AdditiveRegressionModelImpl.java
  Server/src/main/java/rul/models/LSTMModelImpl.java
  Server/src/main/java/rul/models/LinearRegressionModelImpl.java
  Server/src/main/java/rul/models/ModelStrategy.java
  Server/src/main/java/rul/models/ModelsController.java
  Server/src/main/java/rul/models/MultilayerPerceptronModelImpl.java
  Server/src/main/java/rul/models/RandomCommitteeModelImpl.java
  Server/src/main/java/rul/models/RandomForestModelImpl.java
  Server/src/main/java/rul/models/RandomSubSpaceModelImpl.java
  Server/src/main/java/rul/models/SMORegModelImpl.java
  Server/src/main/resources/config.properties
  Server/src/test/java/UnitTests/rul/models/AdditiveRegressionTest.java
  Server/src/test/java/UnitTests/rul/models/LSTMTest.java
  Server/src/test/java/UnitTests/rul/models/LinearRegressionTest.java
  Server/src/test/java/UnitTests/rul/models/MultilayerPerceptronTest.java
  Server/src/test/java/UnitTests/rul/models/RandomCommitteeTest.java
  Server/src/test/java/UnitTests/rul/models/RandomForestTest.java
  Server/src/test/java/UnitTests/rul/models/RandomSubSpaceTest.java
  Server/src/test/java/UnitTests/rul/models/SMORegTest.java
Labels: Pull Request

#281 235 revamp UI
  JavaFXUserInterface/src/main/java/controllers/AddAssetController.java
  JavaFXUserInterface/src/main/java/controllers/AddAssetTypeController.java
  JavaFXUserInterface/src/main/java/controllers/AssetInfoController.java
  JavaFXUserInterface/src/main/java/controllers/AssetTypeController.java
  JavaFXUserInterface/src/main/java/controllers/AssetTypeInfoController.java
  JavaFXUserInterface/src/main/java/controllers/AssetsController.java
  JavaFXUserInterface/src/main/java/controllers/NavigationController.java
  JavaFXUserInterface/src/main/java/external/ModelDAOImpl.java
  JavaFXUserInterface/src/main/java/utilities/CustomDialog.java
  JavaFXUserInterface/src/main/java/utilities/ModelPanes.java
  JavaFXUserInterface/src/main/java/utilities/UIUtilities.java
  JavaFXUserInterface/src/main/resources/AddAsset.fxml
  JavaFXUserInterface/src/main/resources/AddAssetType.fxml
  JavaFXUserInterface/src/main/resources/AssetInfo.fxml
  JavaFXUserInterface/src/main/resources/AssetTypeInfo.fxml
  JavaFXUserInterface/src/main/resources/AssetTypeList.fxml
  JavaFXUserInterface/src/main/resources/Assets.fxml
  JavaFXUserInterface/src/main/resources/Navigation.fxml
  JavaFXUserInterface/src/main/resources/css/revamp/addAsset.css
  JavaFXUserInterface/src/main/resources/css/revamp/addAssetType.css
  JavaFXUserInterface/src/main/resources/css/revamp/assetInfo.css
  JavaFXUserInterface/src/main/resources/css/revamp/assetType.css
  JavaFXUserInterface/src/main/resources/css/revamp/assetTypeInfo.css
  JavaFXUserInterface/src/main/resources/css/revamp/assets.css
  JavaFXUserInterface/src/main/resources/css/revamp/navigation.css
  JavaFXUserInterface/src/main/resources/css/revamp/style.css
  JavaFXUserInterface/src/main/resources/imgs/outline_arrow_back_black_36dp.png
  JavaFXUserInterface/src/main/resources/imgs/outline_exit_to_app_white_36dp.png
Labels: Pull Request

#291 Added sorting mechanism for recommendations
  JavaFXUserInterface/src/main/java/controllers/AssetsController.java
  Server/src/main/java/app/item/Asset.java
Labels: Pull Request

#289 Archive Asset
  JavaFXUserInterface/src/main/java/controllers/AssetInfoController.java
  JavaFXUserInterface/src/main/java/controllers/AssetsController.java
  JavaFXUserInterface/src/main/java/external/AssetDAO.java
  JavaFXUserInterface/src/main/java/external/AssetDAOImpl.java
  JavaFXUserInterface/src/main/java/utilities/CustomDialog.java
  JavaFXUserInterface/src/main/java/utilities/TextConstants.java
  JavaFXUserInterface/src/main/java/utilities/UIUtilities.java
  JavaFXUserInterface/src/main/resources/AssetInfo.fxml
  JavaFXUserInterface/src/main/resources/css/revamp/assetInfo.css
  Server/src/main/java/app/item/AssetAttribute.java
  Server/src/main/resources/config.properties
Labels: Pull Request

#297 [BUG Fixed] F12 - Model/Asset type association logic fixed
  JavaFXUserInterface/src/main/java/controllers/AssetInfoController.java
  JavaFXUserInterface/src/main/java/controllers/AssetTypeInfoController.java
  JavaFXUserInterface/src/main/java/controllers/AssetsController.java
  JavaFXUserInterface/src/main/java/external/ModelDAO.java
  JavaFXUserInterface/src/main/java/external/ModelDAOImpl.java
  JavaFXUserInterface/src/test/java/UnitTests/external/ModelDAOTest.java
Labels: Pull Request

#298 [BugFix] Null value handling for asset type parameter
  JavaFXUserInterface/src/main/java/controllers/AssetTypeInfoController.java
  JavaFXUserInterface/src/main/java/external/AssetTypeDAOImpl.java
  JavaFXUserInterface/src/main/java/utilities/AssetTypeList.java
Labels: Pull Request

#305 #168 Addressing needed UI changes
  JavaFXUserInterface/src/main/java/controllers/AddAssetTypeController.java
  JavaFXUserInterface/src/main/java/controllers/AssetTypeInfoController.java
  JavaFXUserInterface/src/main/resources/AddAssetType.fxml
  JavaFXUserInterface/src/main/resources/AssetTypeInfo.fxml
  JavaFXUserInterface/src/main/resources/css/revamp/addAssetType.css
Labels: Pull Request

#308 #300 added comparator for rawdata table
  JavaFXUserInterface/src/main/java/controllers/AssetInfoController.java
Labels: Pull Request

#307 221 search bar
  JavaFXUserInterface/src/main/java/controllers/AssetsController.java
  JavaFXUserInterface/src/main/resources/Assets.fxml
  JavaFXUserInterface/src/main/resources/css/revamp/assets.css
  JavaFXUserInterface/src/test/java/UnitTests/Controllers/AssetsControllerTest.java
Labels: Pull Request

#304 [Bugfix] Delete action change scene bugfix
  JavaFXUserInterface/src/main/java/app/CBMSApplication.java
  JavaFXUserInterface/src/main/java/controllers/AddAssetController.java
  JavaFXUserInterface/src/main/java/controllers/AssetInfoController.java
  JavaFXUserInterface/src/main/java/controllers/AssetTypeInfoController.java
  JavaFXUserInterface/src/main/java/utilities/CustomDialog.java
  JavaFXUserInterface/src/main/java/utilities/TextConstants.java
Labels: BugFix, Pull Request, refactoring

#306 [BugFix + Refactoring] Input validation logic and display
  JavaFXUserInterface/src/main/java/controllers/AddAssetController.java
  JavaFXUserInterface/src/main/java/controllers/AddAssetTypeController.java
  JavaFXUserInterface/src/main/java/controllers/AssetTypeInfoController.java
  JavaFXUserInterface/src/main/java/utilities/FormInputValidation.java
  JavaFXUserInterface/src/main/java/utilities/UIUtilities.java
  JavaFXUserInterface/src/main/resources/AddAsset.fxml
  JavaFXUserInterface/src/main/resources/AddAssetType.fxml
  JavaFXUserInterface/src/main/resources/AssetTypeInfo.fxml
  JavaFXUserInterface/src/main/resources/css/revamp/style.css
Labels: BugFix, Pull Request, refactoring
