Repository rdsaliba/notorious-eng, pull requests merged in 2021-04, with the labels that each got.

#319 214 UI clean up asset list
  JavaFXUserInterface/src/main/java/controllers/AssetTypeInfoController.java
  JavaFXUserInterface/src/main/java/controllers/AssetsController.java
  JavaFXUserInterface/src/main/resources/Assets.fxml
  JavaFXUserInterface/src/main/resources/css/revamp/assets.css
  JavaFXUserInterface/src/main/resources/imgs/baseline_filter_alt_black_24dp.png
  JavaFXUserInterface/src/main/resources/imgs/baseline_reorder_black_24dp.png
  JavaFXUserInterface/src/main/resources/imgs/baseline_search_black_24dp.png
Labels: Pull Request

#318 #164 E2E System Tests for Features
  JavaFXUserInterface/src/test/java/e2e/com/cbms/app/allfeatures/AllFeaturesTest.java
Labels: Pull Request, System Test

#309 248 images
  JavaFXUserInterface/src/main/java/controllers/AddAssetController.java
  JavaFXUserInterface/src/main/java/controllers/AssetInfoController.java
  JavaFXUserInterface/src/main/java/controllers/AssetsController.java
  JavaFXUserInterface/src/main/java/external/AssetDAO.java
  JavaFXUserInterface/src/main/java/external/AssetDAOImpl.java
  JavaFXUserInterface/src/main/resources/AddAsset.fxml
  JavaFXUserInterface/src/main/resources/AssetInfo.fxml
  JavaFXUserInterface/src/main/resources/css/revamp/addAsset.css
  JavaFXUserInterface/src/main/resources/css/revamp/assets.css
  JavaFXUserInterface/src/main/resources/imgs/default.png
  Server/src/main/java/app/item/Asset.java
  Server/src/main/java/local/AssetDAO.java
  Server/src/main/java/local/AssetDAOImpl.java
  Server/src/main/resources/script/UI-Image.sql
Labels: Pull Request

#320 #137 added filtering functionality
  JavaFXUserInterface/src/main/java/controllers/AssetsController.java
  JavaFXUserInterface/src/main/java/utilities/ThresholdEnum.java
  JavaFXUserInterface/src/main/resources/Assets.fxml
  JavaFXUserInterface/src/main/resources/css/revamp/assets.css
Labels: Pull Request

#321 #138 allows for an asset to be edited
  JavaFXUserInterface/src/main/java/controllers/AssetInfoController.java
  JavaFXUserInterface/src/main/java/external/AssetDAO.java
  JavaFXUserInterface/src/main/java/external/AssetDAOImpl.java
  JavaFXUserInterface/src/main/java/utilities/FormInputValidation.java
  JavaFXUserInterface/src/main/resources/AssetInfo.fxml
  JavaFXUserInterface/src/main/resources/css/revamp/assetInfo.css
  Server/src/main/java/app/item/Asset.java
Labels: Pull Request

#325 #40 Aligning UI elements
  JavaFXUserInterface/src/main/java/controllers/AssetInfoController.java
  JavaFXUserInterface/src/main/resources/AddAsset.fxml
  JavaFXUserInterface/src/main/resources/AssetInfo.fxml
  JavaFXUserInterface/src/main/resources/css/revamp/assetInfo.css
Labels: Pull Request

#323 165 UI clean up asset type list
  JavaFXUserInterface/src/main/java/controllers/AssetTypeController.java
  JavaFXUserInterface/src/main/java/utilities/TextConstants.java
  JavaFXUserInterface/src/main/java/utilities/UIUtilities.java
  JavaFXUserInterface/src/main/resources/AssetTypeList.fxml
  JavaFXUserInterface/src/main/resources/css/revamp/assetType.css
Labels: Pull Request

#326 #160 Custom dialog redesign
  JavaFXUserInterface/src/main/java/utilities/CustomDialog.java
Labels: Pull Request

#327 #277 loading feedback
  JavaFXUserInterface/src/main/java/controllers/AddAssetController.java
  JavaFXUserInterface/src/main/java/controllers/AddAssetTypeController.java
  JavaFXUserInterface/src/main/java/controllers/AssetInfoController.java
  JavaFXUserInterface/src/main/java/controllers/AssetTypeController.java
  JavaFXUserInterface/src/main/java/controllers/AssetTypeInfoController.java
  JavaFXUserInterface/src/main/java/controllers/AssetsController.java
  JavaFXUserInterface/src/main/java/external/AssetDAO.java
  JavaFXUserInterface/src/main/java/external/AssetDAOImpl.java
  JavaFXUserInterface/src/main/java/external/ModelDAO.java
  JavaFXUserInterface/src/main/java/external/ModelDAOImpl.java
  JavaFXUserInterface/src/main/java/utilities/CustomDialog.java
  JavaFXUserInterface/src/main/java/utilities/UIUtilities.java
  JavaFXUserInterface/src/main/java/utilities/services/DeleteAssetTypeService.java
  JavaFXUserInterface/src/main/resources/AddAsset.fxml
  JavaFXUserInterface/src/main/resources/AddAssetType.fxml
  JavaFXUserInterface/src/main/resources/AssetInfo.fxml
  JavaFXUserInterface/src/main/resources/AssetTypeInfo.fxml
  JavaFXUserInterface/src/main/resources/AssetTypeList.fxml
  JavaFXUserInterface/src/main/resources/Assets.fxml
  JavaFXUserInterface/src/main/resources/Navigation.fxml
  JavaFXUserInterface/src/main/resources/css/style.css
  JavaFXUserInterface/src/test/java/UnitTests/external/AssetDAOTest.java
  Server/src/main/java/local/AssetDAO.java
  Server/src/main/java/local/AssetDAOImpl.java
  Server/src/main/resources/script/UI-Image.sql
Labels: Pull Request

#329 SonarQube refactoring on new branch updated with develop (#229)
  JavaFXUserInterface/src/main/java/controllers/AddAssetController.java
  JavaFXUserInterface/src/main/java/controllers/AssetInfoController.java
  JavaFXUserInterface/src/main/java/controllers/AssetTypeController.java
  JavaFXUserInterface/src/main/java/controllers/AssetTypeInfoController.java
  JavaFXUserInterface/src/main/java/controllers/AssetsController.java
  JavaFXUserInterface/src/main/java/controllers/Controller.java
  JavaFXUserInterface/src/main/java/external/AssetDAOImpl.java
  JavaFXUserInterface/src/main/java/external/ModelDAOImpl.java
  JavaFXUserInterface/src/main/java/utilities/CustomDialog.java
  JavaFXUserInterface/src/main/java/utilities/FormInputValidation.java
  JavaFXUserInterface/src/main/java/utilities/TextConstants.java
  JavaFXUserInterface/src/main/java/utilities/UIUtilities.java
  JavaFXUserInterface/src/test/java/e2e/com/cbms/app/allfeatures/AllFeaturesTest.java
Labels: Pull Request, refactoring

#330 [BugFix] Add Asset Type Handling
  JavaFXUserInterface/src/main/java/controllers/AddAssetTypeController.java
  JavaFXUserInterface/src/main/java/controllers/AssetTypeInfoController.java
  JavaFXUserInterface/src/main/java/controllers/AssetsController.java
  JavaFXUserInterface/src/main/java/external/AssetTypeDAO.java
  JavaFXUserInterface/src/main/java/external/AssetTypeDAOImpl.java
  JavaFXUserInterface/src/main/java/external/ModelDAOImpl.java
  JavaFXUserInterface/src/main/resources/css/assetTypeInfo.css
Labels: BugFix, Pull Request
