Repository rdsaliba/notorious-eng, pull requests merged in 2021-02, with the labels that each got.

#243 SonarQube refactoring Sprint 6
  JavaFXUserInterface/src/main/java/CBMSApplication.java
  JavaFXUserInterface/src/main/java/Controllers/AddSystemController.java
  JavaFXUserInterface/src/main/java/Controllers/AddSystemTypeController.java
  JavaFXUserInterface/src/main/java/Controllers/SystemInfoController.java
  JavaFXUserInterface/src/main/java/Controllers/SystemTypeController.java
  JavaFXUserInterface/src/main/java/Controllers/SystemTypeInfoController.java
  JavaFXUserInterface/src/main/java/Controllers/SystemsController.java
  JavaFXUserInterface/src/main/java/Utilities/SystemTypeList.java
  JavaFXUserInterface/src/main/java/Utilities/TextConstants.java
  JavaFXUserInterface/src/main/java/Utilities/UIUtilities.java
  JavaFXUserInterface/src/main/resources/AddSystem.fxml
  JavaFXUserInterface/src/main/resources/AddSystemType.fxml
  JavaFXUserInterface/src/main/resources/SystemInfo.fxml
  JavaFXUserInterface/src/main/resources/SystemTypeInfo.fxml
  JavaFXUserInterface/src/main/resources/SystemTypeList.fxml
  JavaFXUserInterface/src/main/resources/Systems.fxml
  JavaFXUserInterface/src/test/java/AddSystemControllerTest.java
  JavaFXUserInterface/src/test/java/AddSystemTypeControllerTest.java
  JavaFXUserInterface/src/test/java/SystemInfoControllerTest.java
  JavaFXUserInterface/src/test/java/SystemTypeInfoControllerTest.java
  JavaFXUserInterface/src/test/java/SystemsControllerTest.java
  RealTimeDemo/src/main/java/Main.java
  RealTimeDemo/src/main/java/MeasurementDAO.java
  Server/pom.xml
  Server/src/main/java/app/ModelController.java
  Server/src/main/java/app/item/AssetAttribute.java
  Server/src/main/java/app/item/AssetInfo.java
  Server/src/main/java/app/item/AssetType.java
  Server/src/main/java/app/item/TrainedModel.java
  Server/src/main/java/local/AssetDAOImpl.java
  Server/src/main/java/local/AssetTypeDAO.java
  Server/src/main/java/local/AssetTypeDAOImpl.java
  Server/src/main/java/local/ModelDAO.java
  Server/src/main/java/local/ModelDAOImpl.java
  Server/src/main/java/preprocessing/DataPreProcessorImpl.java
Labels: Pull Request

#251 Enhancing security with config properties file
  Server/src/main/java/app/ConfigProperties.java
  Server/src/main/java/local/DatabaseConnection.java
  Server/src/main/resources/config.properties
Labels: Pull Request

#245 Model #3 - Random Forest
  Server/src/main/java/app/ModelController.java
  Server/src/main/java/rul/models/RandomForestModelImpl.java
  Server/src/test/java/rul/models/LSTMTest.java
  Server/src/test/java/rul/models/RandomForestTest.java
Labels: Pull Request

#246 Model #4 - Random Committee
  .gitignore
  .idea/.gitignore
  .idea/encodings.xml
  Server/src/main/java/app/ModelController.java
  Server/src/main/java/rul/models/RandomCommitteeModelImpl.java
  Server/src/test/java/rul/models/RandomCommitteeTest.java
Labels: Pull Request

#255 #234 performance enhancements asset information page
  JavaFXUserInterface/src/main/java/Controllers/SystemInfoController.java
  JavaFXUserInterface/src/main/java/Controllers/SystemsController.java
  JavaFXUserInterface/src/main/java/Utilities/UIUtilities.java
  JavaFXUserInterface/src/main/java/external/AssetDAOImpl.java
  JavaFXUserInterface/src/main/java/external/ModelDAO.java
  JavaFXUserInterface/src/main/java/external/ModelDAOImpl.java
  Server/src/main/java/app/ModelController.java
  Server/src/main/java/local/ModelDAO.java
  Server/src/main/java/local/ModelDAOImpl.java
Labels: Pull Request

#263 #217 UI enhancement - Custom Dialog Boxes
  JavaFXUserInterface/src/main/java/Controllers/AddAssetController.java
  JavaFXUserInterface/src/main/java/Controllers/AssetInfoController.java
  JavaFXUserInterface/src/main/java/Controllers/AssetTypeInfoController.java
  JavaFXUserInterface/src/main/java/Utilities/CustomDialog.java
  JavaFXUserInterface/src/main/java/Utilities/TextConstants.java
Labels: Pull Request, UI, enhancement

#265 #237 Asset Type List to Count
  JavaFXUserInterface/src/main/java/Controllers/AssetTypeController.java
  JavaFXUserInterface/src/main/java/Utilities/AssetTypeList.java
  JavaFXUserInterface/src/main/java/external/AssetTypeDAOImpl.java
  JavaFXUserInterface/src/test/java/e2e/com/cbms/app/AssetTypeInfoTest.java
Labels: Pull Request

#266 Bug fixes
  JavaFXUserInterface/src/main/java/Controllers/AssetInfoController.java
  JavaFXUserInterface/src/main/java/Controllers/AssetsController.java
  JavaFXUserInterface/src/main/java/external/AssetDAOImpl.java
  Server/src/main/java/app/ModelController.java
  Server/src/main/java/local/AssetDAO.java
  Server/src/main/java/local/AssetDAOImpl.java
Labels: Pull Request

#274 #216 evaluating rul models for specific asset type
  .DS_Store
  JavaFXUserInterface/src/main/java/Controllers/AssetTypeInfoController.java
  JavaFXUserInterface/src/main/java/external/ModelDAO.java
  JavaFXUserInterface/src/main/java/external/ModelDAOImpl.java
  JavaFXUserInterface/src/main/resources/AssetTypeInfo.fxml
  Server/src/main/java/app/ModelController.java
  Server/src/main/java/preprocessing/DataPrePreprocessorController.java
  Server/src/main/resources/script/cmbs_scriptsV14/model_evlaution_script.sql
Labels: Pull Request

#273 #253 back functionality
  .DS_Store
  JavaFXUserInterface/src/main/java/Controllers/AddAssetController.java
  JavaFXUserInterface/src/main/java/Controllers/AddAssetTypeController.java
  JavaFXUserInterface/src/main/java/Controllers/AssetInfoController.java
  JavaFXUserInterface/src/main/java/Controllers/AssetTypeController.java
  JavaFXUserInterface/src/main/java/Controllers/AssetTypeInfoController.java
  JavaFXUserInterface/src/main/java/Controllers/AssetsController.java
  JavaFXUserInterface/src/main/resources/AddAsset.fxml
  JavaFXUserInterface/src/main/resources/AddAssetType.fxml
  JavaFXUserInterface/src/main/resources/AssetInfo.fxml
  JavaFXUserInterface/src/main/resources/AssetTypeInfo.fxml
  JavaFXUserInterface/src/main/resources/AssetTypeList.fxml
  JavaFXUserInterface/src/main/resources/imgs/outline_arrow_back_black_18dp.png
Labels: Pull Request, UI
